# Copyright 1996 Acorn Computers Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Makefile for RAMFSFiler
#
# ***********************************
# ***    C h a n g e   L i s t    ***
# ***********************************
# Date       Name         Description
# ----       ----         -----------
# 25-May-94  AMcC         Created.
#
COMPONENT = RAMFSFiler

include StdTools
include AAsmModule

# Dynamic dependencies:
o.CortexA7.RAMFSFiler: s.RAMFSFiler
o.CortexA7.RAMFSFiler: Hdr:ListOpts
o.CortexA7.RAMFSFiler: Hdr:Macros
o.CortexA7.RAMFSFiler: Hdr:System
o.CortexA7.RAMFSFiler: Hdr:SWIs
o.CortexA7.RAMFSFiler: Hdr:CPU.Arch
o.CortexA7.RAMFSFiler: Hdr:Machine.<Machine>
o.CortexA7.RAMFSFiler: Hdr:Machine.Machine
o.CortexA7.RAMFSFiler: Hdr:CPU.Generic26
o.CortexA7.RAMFSFiler: Hdr:CPU.Generic32
o.CortexA7.RAMFSFiler: Hdr:IO.GenericIO
o.CortexA7.RAMFSFiler: Hdr:RISCOS
o.CortexA7.RAMFSFiler: Hdr:Services
o.CortexA7.RAMFSFiler: Hdr:ModHand
o.CortexA7.RAMFSFiler: Hdr:FSNumbers
o.CortexA7.RAMFSFiler: Hdr:HighFSI
o.CortexA7.RAMFSFiler: Hdr:NewErrors
o.CortexA7.RAMFSFiler: Hdr:Wimp
o.CortexA7.RAMFSFiler: Hdr:WimpSpace
o.CortexA7.RAMFSFiler: Hdr:Messages
o.CortexA7.RAMFSFiler: Hdr:Sprite
o.CortexA7.RAMFSFiler: Hdr:VduExt
o.CortexA7.RAMFSFiler: Hdr:Proc
o.CortexA7.RAMFSFiler: Hdr:Variables
o.CortexA7.RAMFSFiler: Hdr:MsgTrans
o.CortexA7.RAMFSFiler: Hdr:MsgMenus
o.CortexA7.RAMFSFiler: Hdr:ResourceFS
o.CortexA7.RAMFSFiler: Hdr:ShareD
o.CortexA7.RAMFSFiler: VersionASM
o.CortexA7.RAMFSFiler: Hdr:HostFS
o.CortexA7.RAMFSFiler: Hdr:Debug
o.CortexA7.RAMFSFiler: s.MsgCode
