# Copyright 1996 Acorn Computers Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Makefile for PipeFS
#
# ************************************
# ***     C h a n g e   L i s t    ***
# ************************************
# Date         Name        Description
# ----         ----        -----------
# 11-Apr-2001  DSC         Created.
#

COMPONENT = PipeFS

include StdTools
include AAsmModule

# Dynamic dependencies:
o.CortexA7.PipeFS: s.PipeFS
o.CortexA7.PipeFS: Hdr:ListOpts
o.CortexA7.PipeFS: Hdr:Macros
o.CortexA7.PipeFS: Hdr:System
o.CortexA7.PipeFS: Hdr:SWIs
o.CortexA7.PipeFS: Hdr:CPU.Arch
o.CortexA7.PipeFS: Hdr:Machine.<Machine>
o.CortexA7.PipeFS: Hdr:Machine.Machine
o.CortexA7.PipeFS: Hdr:CPU.Generic26
o.CortexA7.PipeFS: Hdr:CPU.Generic32
o.CortexA7.PipeFS: Hdr:IO.GenericIO
o.CortexA7.PipeFS: Hdr:RISCOS
o.CortexA7.PipeFS: Hdr:ModHand
o.CortexA7.PipeFS: Hdr:Services
o.CortexA7.PipeFS: Hdr:OSMem
o.CortexA7.PipeFS: Hdr:Proc
o.CortexA7.PipeFS: Hdr:FSNumbers
o.CortexA7.PipeFS: Hdr:HighFSI
o.CortexA7.PipeFS: Hdr:LowFSI
o.CortexA7.PipeFS: Hdr:NewErrors
o.CortexA7.PipeFS: Hdr:FileTypes
o.CortexA7.PipeFS: Hdr:UpCall
o.CortexA7.PipeFS: Hdr:MsgTrans
o.CortexA7.PipeFS: Hdr:Heap
o.CortexA7.PipeFS: VersionASM
o.CortexA7.PipeFS: Hdr:NDRDebug
