# Copyright 1996 Acorn Computers Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Makefile for Pinboard
#
# ***********************************
# ***    C h a n g e   L i s t    ***
# ***********************************
# Date       Name         Description
# ----       ----         -----------
# 14-Mar-01  SNB          Recreated

COMPONENT     = Pinboard
INSTRES_FILES = Templates

include StdTools
include AAsmModule

# Dynamic dependencies:
o.CortexA7.Pinboard: s.Pinboard
o.CortexA7.Pinboard: hdr:ListOpts
o.CortexA7.Pinboard: hdr:Macros
o.CortexA7.Pinboard: hdr:System
o.CortexA7.Pinboard: Hdr:SWIs
o.CortexA7.Pinboard: Hdr:CPU.Arch
o.CortexA7.Pinboard: Hdr:Machine.<Machine>
o.CortexA7.Pinboard: Hdr:Machine.Machine
o.CortexA7.Pinboard: Hdr:CPU.Generic26
o.CortexA7.Pinboard: Hdr:CPU.Generic32
o.CortexA7.Pinboard: Hdr:IO.GenericIO
o.CortexA7.Pinboard: Hdr:RISCOS
o.CortexA7.Pinboard: hdr:ModHand
o.CortexA7.Pinboard: hdr:Services
o.CortexA7.Pinboard: hdr:VduExt
o.CortexA7.Pinboard: hdr:FSNumbers
o.CortexA7.Pinboard: hdr:NewErrors
o.CortexA7.Pinboard: hdr:Territory
o.CortexA7.Pinboard: hdr:Variables
o.CortexA7.Pinboard: hdr:Proc
o.CortexA7.Pinboard: hdr:Sprite
o.CortexA7.Pinboard: hdr:Wimp
o.CortexA7.Pinboard: hdr:WimpSpace
o.CortexA7.Pinboard: hdr:Messages
o.CortexA7.Pinboard: hdr:FilerAct
o.CortexA7.Pinboard: hdr:Machine.<Machine>
o.CortexA7.Pinboard: Hdr:Machine.Machine
o.CortexA7.Pinboard: hdr:CMOS
o.CortexA7.Pinboard: hdr:HighFSI
o.CortexA7.Pinboard: hdr:FileTypes
o.CortexA7.Pinboard: hdr:MsgTrans
o.CortexA7.Pinboard: hdr:MsgMenus
o.CortexA7.Pinboard: hdr:ResourceFS
o.CortexA7.Pinboard: hdr:ColourTran
o.CortexA7.Pinboard: hdr:DragASprit
o.CortexA7.Pinboard: hdr:Hourglass
o.CortexA7.Pinboard: hdr:HostFS
o.CortexA7.Pinboard: hdr:NdrDebug
o.CortexA7.Pinboard: hdr:Switcher
o.CortexA7.Pinboard: Hdr:Font
o.CortexA7.Pinboard: Hdr:SprExtend
o.CortexA7.Pinboard: Hdr:OSBytes
o.CortexA7.Pinboard: VersionASM
o.CortexA7.Pinboard: s.ModHead
o.CortexA7.Pinboard: s.StartLoop
o.CortexA7.Pinboard: s.Messages
o.CortexA7.Pinboard: s.Help
o.CortexA7.Pinboard: s.Iconize
o.CortexA7.Pinboard: s.Save
o.CortexA7.Pinboard: s.Backdrop
o.CortexA7.Pinboard: s.Icons
o.CortexA7.Pinboard: s.Buffered
o.CortexA7.Pinboard: s.Mouse
o.CortexA7.Pinboard: s.Drag
o.CortexA7.Pinboard: s.Menu
o.CortexA7.Pinboard: s.MenuSelect
o.CortexA7.Pinboard: s.Tidy
o.CortexA7.Pinboard: s.Tail
