# Copyright 1996 Acorn Computers Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Makefile for WaveSynth
#
# ***********************************
# ***    C h a n g e   L i s t    ***
# ***********************************
# Date       Name         Description
# ----       ----         -----------
# 07-Mar-01  SNB          Recreated

#
# Program specific options:
#
COMPONENT = WaveSynth

include StdTools
include AAsmModule

# Dynamic dependencies:
o.CortexA7.WaveSynth: s.WaveSynth
o.CortexA7.WaveSynth: Hdr:ListOpts
o.CortexA7.WaveSynth: Hdr:Macros
o.CortexA7.WaveSynth: Hdr:System
o.CortexA7.WaveSynth: Hdr:SWIs
o.CortexA7.WaveSynth: Hdr:CPU.Arch
o.CortexA7.WaveSynth: Hdr:Machine.<Machine>
o.CortexA7.WaveSynth: Hdr:Machine.Machine
o.CortexA7.WaveSynth: Hdr:CPU.Generic26
o.CortexA7.WaveSynth: Hdr:CPU.Generic32
o.CortexA7.WaveSynth: Hdr:IO.GenericIO
o.CortexA7.WaveSynth: Hdr:RISCOS
o.CortexA7.WaveSynth: Hdr:Machine.<Machine>
o.CortexA7.WaveSynth: Hdr:Machine.Machine
o.CortexA7.WaveSynth: Hdr:ModHand
o.CortexA7.WaveSynth: Hdr:PublicWS
o.CortexA7.WaveSynth: Hdr:Sound
o.CortexA7.WaveSynth: Hdr:Proc
o.CortexA7.WaveSynth: Hdr:MsgTrans
o.CortexA7.WaveSynth: Hdr:Services
o.CortexA7.WaveSynth: Hdr:HighFSI
o.CortexA7.WaveSynth: VersionASM
o.CortexA7.WaveSynth: s.MsgCode
