# Copyright 1996 Acorn Computers Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Makefile for CDFSFiler
#

COMPONENT = CDFSFiler
INSTRES_FILES = Player Templates
ASMDEFINES = -pd "SuffixSprite SETS \"${SUFFIX_SPRITE}\"" -pd "SuffixTemplate SETS \"${SUFFIX_TEMPLATE}\""

include AAsmModule

# Dynamic dependencies:
o.CortexA7.CDFSFiler: s.CDFSFiler
o.CortexA7.CDFSFiler: Hdr:ListOpts
o.CortexA7.CDFSFiler: Hdr:Macros
o.CortexA7.CDFSFiler: Hdr:System
o.CortexA7.CDFSFiler: Hdr:SWIs
o.CortexA7.CDFSFiler: Hdr:CPU.Arch
o.CortexA7.CDFSFiler: Hdr:Machine.<Machine>
o.CortexA7.CDFSFiler: Hdr:Machine.Machine
o.CortexA7.CDFSFiler: Hdr:CPU.Generic26
o.CortexA7.CDFSFiler: Hdr:CPU.Generic32
o.CortexA7.CDFSFiler: Hdr:IO.GenericIO
o.CortexA7.CDFSFiler: Hdr:RISCOS
o.CortexA7.CDFSFiler: Hdr:Services
o.CortexA7.CDFSFiler: Hdr:ModHand
o.CortexA7.CDFSFiler: Hdr:FSNumbers
o.CortexA7.CDFSFiler: Hdr:HighFSI
o.CortexA7.CDFSFiler: Hdr:NewErrors
o.CortexA7.CDFSFiler: Hdr:Wimp
o.CortexA7.CDFSFiler: Hdr:WimpSpace
o.CortexA7.CDFSFiler: Hdr:Messages
o.CortexA7.CDFSFiler: Hdr:Sprite
o.CortexA7.CDFSFiler: Hdr:VduExt
o.CortexA7.CDFSFiler: Hdr:Variables
o.CortexA7.CDFSFiler: Hdr:Proc
o.CortexA7.CDFSFiler: Hdr:ShareD
o.CortexA7.CDFSFiler: Hdr:MsgMenus
o.CortexA7.CDFSFiler: Hdr:MsgTrans
o.CortexA7.CDFSFiler: Hdr:ResourceFS
o.CortexA7.CDFSFiler: Hdr:CDROM
o.CortexA7.CDFSFiler: Hdr:CDErrors
o.CortexA7.CDFSFiler: Hdr:CDFS
o.CortexA7.CDFSFiler: Hdr:Hourglass
o.CortexA7.CDFSFiler: Hdr:HostFS
o.CortexA7.CDFSFiler: Hdr:NdrDebug
o.CortexA7.CDFSFiler: Hdr:DDVMacros
o.CortexA7.CDFSFiler: hdr.Icons
o.CortexA7.CDFSFiler: VersionASM
