# Copyright 1996 Acorn Computers Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Makefile for DragAnObj
#
# ***********************************
# ***    C h a n g e   L i s t    ***
# ***********************************
# Date       Name         Description
# ----       ----         -----------
# 14-Mar-01  SNB          Recreated.

COMPONENT = DragAnObj
HEADER1   = DragAnObj
RESOURCES = no

include StdTools
include AAsmModule

# Dynamic dependencies:
o.CortexA7.DragAnObj: s.DragAnObj
o.CortexA7.DragAnObj: hdr:ListOpts
o.CortexA7.DragAnObj: hdr:Macros
o.CortexA7.DragAnObj: hdr:System
o.CortexA7.DragAnObj: Hdr:SWIs
o.CortexA7.DragAnObj: Hdr:CPU.Arch
o.CortexA7.DragAnObj: Hdr:Machine.<Machine>
o.CortexA7.DragAnObj: Hdr:Machine.Machine
o.CortexA7.DragAnObj: Hdr:CPU.Generic26
o.CortexA7.DragAnObj: Hdr:CPU.Generic32
o.CortexA7.DragAnObj: Hdr:IO.GenericIO
o.CortexA7.DragAnObj: Hdr:RISCOS
o.CortexA7.DragAnObj: hdr:ModHand
o.CortexA7.DragAnObj: hdr:Services
o.CortexA7.DragAnObj: hdr:Proc
o.CortexA7.DragAnObj: hdr:Wimp
o.CortexA7.DragAnObj: hdr:Sprite
o.CortexA7.DragAnObj: hdr:DragASprit
o.CortexA7.DragAnObj: hdr:MsgTrans
o.CortexA7.DragAnObj: hdr:FSNumbers
o.CortexA7.DragAnObj: hdr:NewErrors
o.CortexA7.DragAnObj: hdr:OSRSI6
o.CortexA7.DragAnObj: VersionASM
