# Copyright 1996 Acorn Computers Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Makefile for ResourceFS
#

COMPONENT = ResourceFS
HEADER1   = ResourceFS

include AAsmModule

# Dynamic dependencies:
o.CortexA7.ResourceFS: s.ResourceFS
o.CortexA7.ResourceFS: Hdr:ListOpts
o.CortexA7.ResourceFS: Hdr:Macros
o.CortexA7.ResourceFS: Hdr:System
o.CortexA7.ResourceFS: Hdr:SWIs
o.CortexA7.ResourceFS: Hdr:CPU.Arch
o.CortexA7.ResourceFS: Hdr:Machine.<Machine>
o.CortexA7.ResourceFS: Hdr:Machine.Machine
o.CortexA7.ResourceFS: Hdr:CPU.Generic26
o.CortexA7.ResourceFS: Hdr:CPU.Generic32
o.CortexA7.ResourceFS: Hdr:IO.GenericIO
o.CortexA7.ResourceFS: Hdr:RISCOS
o.CortexA7.ResourceFS: Hdr:ModHand
o.CortexA7.ResourceFS: Hdr:Services
o.CortexA7.ResourceFS: Hdr:Proc
o.CortexA7.ResourceFS: Hdr:FSNumbers
o.CortexA7.ResourceFS: Hdr:HighFSI
o.CortexA7.ResourceFS: Hdr:LowFSI
o.CortexA7.ResourceFS: Hdr:NewErrors
o.CortexA7.ResourceFS: Hdr:Variables
o.CortexA7.ResourceFS: Hdr:Wimp
o.CortexA7.ResourceFS: Hdr:ResourceFS
o.CortexA7.ResourceFS: Hdr:UpCall
o.CortexA7.ResourceFS: Hdr:MsgTrans
o.CortexA7.ResourceFS: Hdr:Territory
o.CortexA7.ResourceFS: VersionASM
o.CortexA7.ResourceFS: Hdr:NdrDebug
o.CortexA7.ResourceFS: s.MsgCode
