# Copyright 1996 Acorn Computers Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Makefile for Font Manager
#
# ***********************************
# ***    C h a n g e   L i s t    ***
# ***********************************
# Date       Name         Description
# ----       ----         -----------
# 25-May-94  AMcC         Created.
#

COMPONENT = FontManager
TARGET    = Fonts
HEADER1   = Font

include StdTools
include AAsmModule

# Dynamic dependencies:
o.CortexA7.Fonts: s.Fonts
o.CortexA7.Fonts: hdr:ListOpts
o.CortexA7.Fonts: hdr:Macros
o.CortexA7.Fonts: hdr:System
o.CortexA7.Fonts: Hdr:SWIs
o.CortexA7.Fonts: Hdr:CPU.Arch
o.CortexA7.Fonts: Hdr:Machine.<Machine>
o.CortexA7.Fonts: Hdr:Machine.Machine
o.CortexA7.Fonts: Hdr:CPU.Generic26
o.CortexA7.Fonts: Hdr:CPU.Generic32
o.CortexA7.Fonts: Hdr:IO.GenericIO
o.CortexA7.Fonts: Hdr:RISCOS
o.CortexA7.Fonts: hdr:Machine.<Machine>
o.CortexA7.Fonts: Hdr:Machine.Machine
o.CortexA7.Fonts: hdr:CPU.Arch
o.CortexA7.Fonts: hdr:CMOS
o.CortexA7.Fonts: hdr:ModHand
o.CortexA7.Fonts: hdr:Proc
o.CortexA7.Fonts: hdr:Services
o.CortexA7.Fonts: hdr:FSNumbers
o.CortexA7.Fonts: Hdr:HighFSI
o.CortexA7.Fonts: hdr:NewErrors
o.CortexA7.Fonts: hdr:Variables
o.CortexA7.Fonts: hdr:VduExt
o.CortexA7.Fonts: hdr:PDriver
o.CortexA7.Fonts: hdr:Font
o.CortexA7.Fonts: hdr:Super
o.CortexA7.Fonts: hdr:MsgTrans
o.CortexA7.Fonts: hdr:Sprite
o.CortexA7.Fonts: hdr:Draw
o.CortexA7.Fonts: hdr:ColourTran
o.CortexA7.Fonts: hdr:Wimp
o.CortexA7.Fonts: hdr:WimpSpace
o.CortexA7.Fonts: hdr:Hourglass
o.CortexA7.Fonts: hdr:FileTypes
o.CortexA7.Fonts: hdr:Territory
o.CortexA7.Fonts: hdr:Internatio
o.CortexA7.Fonts: hdr:NDRDebug
o.CortexA7.Fonts: hdr:PublicWS
o.CortexA7.Fonts: hdr:hostfs
o.CortexA7.Fonts: VersionASM
o.CortexA7.Fonts: s.Errors
o.CortexA7.Fonts: s.Fonts01
o.CortexA7.Fonts: s.FontsM
o.CortexA7.Fonts: s.ListFonts
o.CortexA7.Fonts: s.Fonts02
o.CortexA7.Fonts: s.Fonts03
o.CortexA7.Fonts: s.Font_Arith
o.CortexA7.Fonts: s.Font_BasFP
o.CortexA7.Fonts: s.Funcache
o.CortexA7.Fonts: s.Fonts04
o.CortexA7.Fonts: s.Encoding
o.CortexA7.Fonts: s.Blending
o.CortexA7.Fonts: hdr:ITable
o.CortexA7.Fonts: s.BlendingS
o.CortexA7.Fonts: s.BlendingS
