# Copyright 1996 Acorn Computers Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Makefile for Percussion
#
# ***********************************
# ***    C h a n g e   L i s t    ***
# ***********************************
# Date       Name         Description
# ----       ----         -----------
# 07-Mar-01  SNB          Recreated
#

COMPONENT = Percussion

include StdTools
include AAsmModule

# Dynamic dependencies:
o.CortexA7.Percussion: s.Percussion
o.CortexA7.Percussion: Hdr:ListOpts
o.CortexA7.Percussion: Hdr:Macros
o.CortexA7.Percussion: Hdr:System
o.CortexA7.Percussion: Hdr:SWIs
o.CortexA7.Percussion: Hdr:CPU.Arch
o.CortexA7.Percussion: Hdr:Machine.<Machine>
o.CortexA7.Percussion: Hdr:Machine.Machine
o.CortexA7.Percussion: Hdr:CPU.Generic26
o.CortexA7.Percussion: Hdr:CPU.Generic32
o.CortexA7.Percussion: Hdr:IO.GenericIO
o.CortexA7.Percussion: Hdr:RISCOS
o.CortexA7.Percussion: Hdr:ModHand
o.CortexA7.Percussion: Hdr:Machine.<Machine>
o.CortexA7.Percussion: Hdr:Machine.Machine
o.CortexA7.Percussion: Hdr:PublicWS
o.CortexA7.Percussion: Hdr:Sound
o.CortexA7.Percussion: Hdr:Proc
o.CortexA7.Percussion: Hdr:MsgTrans
o.CortexA7.Percussion: Hdr:Services
o.CortexA7.Percussion: VersionASM
o.CortexA7.Percussion: s.MsgCode
