# Copyright 1996 Acorn Computers Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Makefile for FilerSWIs
#
# ***********************************
# ***    C h a n g e   L i s t    ***
# ***********************************
# Date       Name         Description
# ----       ----         -----------
# 14-Mar-01  SNB          Recreated.
#

COMPONENT = FilerSWIs
RESOURCES = no

include StdTools
include AAsmModule

# Dynamic dependencies:
o.CortexA7.FilerSWIs: s.FilerSWIs
o.CortexA7.FilerSWIs: Hdr:ListOpts
o.CortexA7.FilerSWIs: Hdr:Macros
o.CortexA7.FilerSWIs: Hdr:System
o.CortexA7.FilerSWIs: Hdr:SWIs
o.CortexA7.FilerSWIs: Hdr:CPU.Arch
o.CortexA7.FilerSWIs: Hdr:Machine.<Machine>
o.CortexA7.FilerSWIs: Hdr:Machine.Machine
o.CortexA7.FilerSWIs: Hdr:CPU.Generic26
o.CortexA7.FilerSWIs: Hdr:CPU.Generic32
o.CortexA7.FilerSWIs: Hdr:IO.GenericIO
o.CortexA7.FilerSWIs: Hdr:RISCOS
o.CortexA7.FilerSWIs: Hdr:FSNumbers
o.CortexA7.FilerSWIs: Hdr:NewErrors
o.CortexA7.FilerSWIs: Hdr:ModHand
o.CortexA7.FilerSWIs: Hdr:Wimp
o.CortexA7.FilerSWIs: Hdr:WimpSpace
o.CortexA7.FilerSWIs: Hdr:Messages
o.CortexA7.FilerSWIs: Hdr:Proc
o.CortexA7.FilerSWIs: Hdr:FilerAct
o.CortexA7.FilerSWIs: Hdr:MsgTrans
o.CortexA7.FilerSWIs: VersionASM
