# Copyright 1996 Acorn Computers Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Makefile for SerialSpt
#
# ***********************************
# ***    C h a n g e   L i s t    ***
# ***********************************
# Date       Name         Description
# ----       ----         -----------
# 09-Mar-01  SNB          Recreated
#

COMPONENT = SerialDeviceSupport
TARGET    = SerialSpt
RESOURCES = no
HEADER1   = SerialOp

include StdTools
include AAsmModule

# Dynamic dependencies:
o.CortexA7.SerialSpt: s.SerialSpt
o.CortexA7.SerialSpt: Hdr:ListOpts
o.CortexA7.SerialSpt: Hdr:Macros
o.CortexA7.SerialSpt: Hdr:DDVMacros
o.CortexA7.SerialSpt: Hdr:System
o.CortexA7.SerialSpt: Hdr:SWIs
o.CortexA7.SerialSpt: Hdr:CPU.Arch
o.CortexA7.SerialSpt: Hdr:Machine.<Machine>
o.CortexA7.SerialSpt: Hdr:Machine.Machine
o.CortexA7.SerialSpt: Hdr:CPU.Generic26
o.CortexA7.SerialSpt: Hdr:CPU.Generic32
o.CortexA7.SerialSpt: Hdr:IO.GenericIO
o.CortexA7.SerialSpt: Hdr:RISCOS
o.CortexA7.SerialSpt: Hdr:ModHand
o.CortexA7.SerialSpt: Hdr:FSNumbers
o.CortexA7.SerialSpt: Hdr:NewErrors
o.CortexA7.SerialSpt: Hdr:Machine.<Machine>
o.CortexA7.SerialSpt: Hdr:Machine.Machine
o.CortexA7.SerialSpt: Hdr:CMOS
o.CortexA7.SerialSpt: Hdr:Symbols
o.CortexA7.SerialSpt: Hdr:Services
o.CortexA7.SerialSpt: Hdr:DeviceFS
o.CortexA7.SerialSpt: Hdr:Serial
o.CortexA7.SerialSpt: Hdr:RS423
o.CortexA7.SerialSpt: Hdr:HostFS
o.CortexA7.SerialSpt: Hdr:NdrDebug
o.CortexA7.SerialSpt: Hdr:MsgTrans
o.CortexA7.SerialSpt: Hdr:UpCall
o.CortexA7.SerialSpt: Hdr:Proc
o.CortexA7.SerialSpt: Hdr:SerialOp
o.CortexA7.SerialSpt: VersionASM
o.CortexA7.SerialSpt: s.Macros
o.CortexA7.SerialSpt: s.Errors
