# Copyright 1996 Acorn Computers Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Makefile for BBCEconet
#
# ***********************************
# ***    C h a n g e   L i s t    ***
# ***********************************
# Date       Name         Description
# ----       ----         -----------
# 10-Nov-02  RPS          Stolen from filer
#

COMPONENT     = BBCEconet
RESOURCES     = No

include StdTools
include AAsmModule

# Dynamic dependencies:
o.CortexA7.BBCEconet: s.BBCEconet
o.CortexA7.BBCEconet: Hdr:ListOpts
o.CortexA7.BBCEconet: Hdr:Macros
o.CortexA7.BBCEconet: Hdr:System
o.CortexA7.BBCEconet: Hdr:SWIs
o.CortexA7.BBCEconet: Hdr:CPU.Arch
o.CortexA7.BBCEconet: Hdr:Machine.<Machine>
o.CortexA7.BBCEconet: Hdr:Machine.Machine
o.CortexA7.BBCEconet: Hdr:CPU.Generic26
o.CortexA7.BBCEconet: Hdr:CPU.Generic32
o.CortexA7.BBCEconet: Hdr:IO.GenericIO
o.CortexA7.BBCEconet: Hdr:RISCOS
o.CortexA7.BBCEconet: Hdr:Debug
o.CortexA7.BBCEconet: Hdr:ModHand
o.CortexA7.BBCEconet: Hdr:FSNumbers
o.CortexA7.BBCEconet: Hdr:NewErrors
o.CortexA7.BBCEconet: Hdr:Services
o.CortexA7.BBCEconet: Hdr:Econet
o.CortexA7.BBCEconet: Hdr:MsgTrans
o.CortexA7.BBCEconet: Hdr:Symbols
o.CortexA7.BBCEconet: Hdr:CPU.Arch
o.CortexA7.BBCEconet: VersionASM
o.CortexA7.BBCEconet: s.Interface
