# Copyright 1997 Acorn Computers Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Makefile for PlainArgv
#

COMPONENT = PlainArgv
OBJS      = ToBuffer StrTok Get Find CopyPArgv CFilename
HDRS      = PlainArgv StrTok

include CLibrary

# Dynamic dependencies:
oz.ToBuffer:	c.ToBuffer
oz.ToBuffer:	C:Desk.h.Debug
oz.ToBuffer:	C:Desk.h.Core
oz.ToBuffer:	C:h.kernel
oz.ToBuffer:	C:PlainArgv.h.PlainArgv
oz.ToBuffer:	C:Desk.h.DeskMem
oz.StrTok:	c.StrTok
oz.StrTok:	C:Desk.h.DeskMem
oz.StrTok:	C:Desk.h.Core
oz.StrTok:	C:h.kernel
oz.StrTok:	C:PlainArgv.h.StrTok
oz.Get:	c.Get
oz.Get:	C:PlainArgv.h.PlainArgv
oz.Get:	C:Desk.h.DeskMem
oz.Get:	C:Desk.h.Core
oz.Get:	C:h.kernel
oz.Find:	c.Find
oz.Find:	C:Desk.h.Debug
oz.Find:	C:Desk.h.Core
oz.Find:	C:h.kernel
oz.Find:	C:Desk.h.DeskMem
oz.Find:	C:Desk.h.Error
oz.Find:	C:Desk.h.Error2
oz.Find:	C:Desk.h.JumpRaw
oz.Find:	C:PlainArgv.h.PlainArgv
oz.CopyPArgv:	c.CopyPArgv
oz.CopyPArgv:	C:h.kernel
oz.CopyPArgv:	C:PlainArgv.h.PlainArgv
oz.CopyPArgv:	C:Desk.h.DeskMem
oz.CopyPArgv:	C:Desk.h.Core
oz.CopyPArgv:	C:h.kernel
oz.CFilename:	c.CFilename
oz.CFilename:	C:h.kernel
oz.CFilename:	C:Desk.h.Filing
oz.CFilename:	C:Desk.h.Core
oz.CFilename:	C:h.kernel
oz.CFilename:	C:Desk.h.Debug
oz.CFilename:	C:PlainArgv.h.PlainArgv
oz.CFilename:	C:Desk.h.DeskMem
o.ToBuffer:	c.ToBuffer
o.ToBuffer:	C:Desk.h.Debug
o.ToBuffer:	C:Desk.h.Core
o.ToBuffer:	C:h.kernel
o.ToBuffer:	C:PlainArgv.h.PlainArgv
o.ToBuffer:	C:Desk.h.DeskMem
o.StrTok:	c.StrTok
o.StrTok:	C:Desk.h.DeskMem
o.StrTok:	C:Desk.h.Core
o.StrTok:	C:h.kernel
o.StrTok:	C:PlainArgv.h.StrTok
o.Get:	c.Get
o.Get:	C:PlainArgv.h.PlainArgv
o.Get:	C:Desk.h.DeskMem
o.Get:	C:Desk.h.Core
o.Get:	C:h.kernel
o.Find:	c.Find
o.Find:	C:Desk.h.Debug
o.Find:	C:Desk.h.Core
o.Find:	C:h.kernel
o.Find:	C:Desk.h.DeskMem
o.Find:	C:Desk.h.Error
o.Find:	C:Desk.h.Error2
o.Find:	C:Desk.h.JumpRaw
o.Find:	C:PlainArgv.h.PlainArgv
o.CopyPArgv:	c.CopyPArgv
o.CopyPArgv:	C:h.kernel
o.CopyPArgv:	C:PlainArgv.h.PlainArgv
o.CopyPArgv:	C:Desk.h.DeskMem
o.CopyPArgv:	C:Desk.h.Core
o.CopyPArgv:	C:h.kernel
o.CFilename:	c.CFilename
o.CFilename:	C:h.kernel
o.CFilename:	C:Desk.h.Filing
o.CFilename:	C:Desk.h.Core
o.CFilename:	C:h.kernel
o.CFilename:	C:Desk.h.Debug
o.CFilename:	C:PlainArgv.h.PlainArgv
o.CFilename:	C:Desk.h.DeskMem
