# Copyright 1996 Acorn Computers Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Makefile for NetFiler
#
# ************************************
# ***     C h a n g e   L i s t    ***
# ************************************
# Date         Name        Description
# ----         ----        -----------
# 20-Dec-2002  KJB         Created.
#

COMPONENT     = NetFiler
INSTRES_FILES = Templates

include StdTools
include AAsmModule

# Dynamic dependencies:
o.CortexA7.NetFiler: s.NetFiler
o.CortexA7.NetFiler: Hdr:ListOpts
o.CortexA7.NetFiler: Hdr:Macros
o.CortexA7.NetFiler: Hdr:System
o.CortexA7.NetFiler: Hdr:SWIs
o.CortexA7.NetFiler: Hdr:CPU.Arch
o.CortexA7.NetFiler: Hdr:Machine.<Machine>
o.CortexA7.NetFiler: Hdr:Machine.Machine
o.CortexA7.NetFiler: Hdr:CPU.Generic26
o.CortexA7.NetFiler: Hdr:CPU.Generic32
o.CortexA7.NetFiler: Hdr:IO.GenericIO
o.CortexA7.NetFiler: Hdr:RISCOS
o.CortexA7.NetFiler: Hdr:Services
o.CortexA7.NetFiler: Hdr:CMOS
o.CortexA7.NetFiler: Hdr:ModHand
o.CortexA7.NetFiler: Hdr:FSNumbers
o.CortexA7.NetFiler: Hdr:HighFSI
o.CortexA7.NetFiler: Hdr:NewErrors
o.CortexA7.NetFiler: Hdr:PublicWS
o.CortexA7.NetFiler: Hdr:Wimp
o.CortexA7.NetFiler: Hdr:WimpSpace
o.CortexA7.NetFiler: Hdr:Messages
o.CortexA7.NetFiler: Hdr:Sprite
o.CortexA7.NetFiler: Hdr:VduExt
o.CortexA7.NetFiler: Hdr:Econet
o.CortexA7.NetFiler: Hdr:Proc
o.CortexA7.NetFiler: Hdr:Variables
o.CortexA7.NetFiler: Hdr:MsgTrans
o.CortexA7.NetFiler: Hdr:MsgMenus
o.CortexA7.NetFiler: Hdr:ResourceFS
o.CortexA7.NetFiler: VersionASM
o.CortexA7.NetFiler: Hdr:NDRDebug
