# Copyright 1996 Acorn Computers Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Makefile for ResFiler
#
# ***********************************
# ***    C h a n g e   L i s t    ***
# ***********************************
# Date       Name         Description
# ----       ----         -----------
# 14-May-01  SNB          Recreated.
#
COMPONENT = ResourceFiler
TARGET    = ResFiler

include StdTools
include AAsmModule

# Dynamic dependencies:
o.CortexA7.ResFiler: s.ResFiler
o.CortexA7.ResFiler: Hdr:ListOpts
o.CortexA7.ResFiler: Hdr:Macros
o.CortexA7.ResFiler: Hdr:System
o.CortexA7.ResFiler: Hdr:SWIs
o.CortexA7.ResFiler: Hdr:CPU.Arch
o.CortexA7.ResFiler: Hdr:Machine.<Machine>
o.CortexA7.ResFiler: Hdr:Machine.Machine
o.CortexA7.ResFiler: Hdr:CPU.Generic26
o.CortexA7.ResFiler: Hdr:CPU.Generic32
o.CortexA7.ResFiler: Hdr:IO.GenericIO
o.CortexA7.ResFiler: Hdr:RISCOS
o.CortexA7.ResFiler: Hdr:Services
o.CortexA7.ResFiler: Hdr:ModHand
o.CortexA7.ResFiler: Hdr:CMOS
o.CortexA7.ResFiler: Hdr:OsBytes
o.CortexA7.ResFiler: Hdr:FSNumbers
o.CortexA7.ResFiler: Hdr:NewErrors
o.CortexA7.ResFiler: Hdr:HighFSI
o.CortexA7.ResFiler: Hdr:Wimp
o.CortexA7.ResFiler: Hdr:WimpSpace
o.CortexA7.ResFiler: Hdr:Messages
o.CortexA7.ResFiler: Hdr:Sprite
o.CortexA7.ResFiler: Hdr:VduExt
o.CortexA7.ResFiler: Hdr:Proc
o.CortexA7.ResFiler: Hdr:Variables
o.CortexA7.ResFiler: Hdr:MsgTrans
o.CortexA7.ResFiler: Hdr:MsgMenus
o.CortexA7.ResFiler: Hdr:ResourceFS
o.CortexA7.ResFiler: VersionASM
