# Copyright 1996 Acorn Computers Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Makefile for SystemDevs
#
# ***********************************
# ***    C h a n g e   L i s t    ***
# ***********************************
# Date       Name         Description
# ----       ----         -----------
# 09-Mar-01  SNB          Recreated

#
# Program specific options:
#
COMPONENT = SystemDevices
TARGET    = SystemDevs

include StdTools
include AAsmModule

# Dynamic dependencies:
o.CortexA7.SystemDevs: s.SystemDevs
o.CortexA7.SystemDevs: Hdr:ListOpts
o.CortexA7.SystemDevs: Hdr:Macros
o.CortexA7.SystemDevs: Hdr:System
o.CortexA7.SystemDevs: Hdr:SWIs
o.CortexA7.SystemDevs: Hdr:CPU.Arch
o.CortexA7.SystemDevs: Hdr:Machine.<Machine>
o.CortexA7.SystemDevs: Hdr:Machine.Machine
o.CortexA7.SystemDevs: Hdr:CPU.Generic26
o.CortexA7.SystemDevs: Hdr:CPU.Generic32
o.CortexA7.SystemDevs: Hdr:IO.GenericIO
o.CortexA7.SystemDevs: Hdr:RISCOS
o.CortexA7.SystemDevs: Hdr:ModHand
o.CortexA7.SystemDevs: Hdr:Services
o.CortexA7.SystemDevs: Hdr:Proc
o.CortexA7.SystemDevs: Hdr:FSNumbers
o.CortexA7.SystemDevs: Hdr:HighFSI
o.CortexA7.SystemDevs: Hdr:LowFSI
o.CortexA7.SystemDevs: Hdr:NewErrors
o.CortexA7.SystemDevs: Hdr:OsBytes
o.CortexA7.SystemDevs: Hdr:CMOS
o.CortexA7.SystemDevs: Hdr:Variables
o.CortexA7.SystemDevs: Hdr:MsgTrans
o.CortexA7.SystemDevs: Hdr:ResourceFS
o.CortexA7.SystemDevs: VersionASM
o.CortexA7.SystemDevs: s.MsgCode
